### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by KevinHurd** [solsniperr/sol-sniper-bot#3]
Hi,

we have it up and running (thank you). But we get this error...

/home/ec2-user/sol-sniper-bot/ssb_start.ts:37
const network = 'mainnet-beta';
           ^
TypeError: Cannot read properties of undefined (reading 'isZero')
    at /home/ec2-user/sol-sniper-bot/ssb_start.ts:146:48
    at Generator.next (<anonymous>)
    at /home/ec2-user/sol-sniper-bot/ssb_start.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ec2-user/sol-sniper-bot/ssb_start.ts:37:12)
    at init (/home/ec2-user/sol-sniper-bot/ssb_start.ts:89:12)
    at /home/ec2-user/sol-sniper-bot/ssb_start.ts:504:9
    at Generator.next (<anonymous>)
    at /home/ec2-user/sol-sniper-bot/ssb_start.ts:41:71
    at new Promise (<anonymous>)

Can you please help?

We think this relates to... but not 100% sure...

quoteMinPoolSizeAmount); 
quoteMaxPoolSizeAmount;

Thanks
Kev

**Comment by solsniperr** [comment]
is your .env configured correctly ?

**Comment by KevinHurd** [comment]
hi, thanks for coming back to me. We have it up and running now on our aws linux box, and have had successful transactions. 
Although we are now coming across memory issues, but thats for us to investigate and looking at server sizing etc. thanks again.

**Comment by KevinHurd** [comment]
although we get this error a lot. "type": "TransactionExpiredBlockheightExceededError",  "message": "Signature 3R9Bd8WsG4A6syZWFNGp6Ahd6X3mYiwcXh9kN2Npv7pTHBWEsHnmoSgZZ8PKD2YMnsq6mnEBHtgc8KobPRNBvNqg has expired: block height exceeded.",

Have you had this before? What was the best resolution?
